version: '3.8'

services:
  gophermart:
    ports:
      - '8181:80'

  accrual:
    ports:
      - '8282:80'

  postgres:
    ports:
      - '5432:5432'

  migrate:
    image: migrate/migrate:4
    volumes:
      - ./migrations/postgres:/migrations
    command: [ "-path", "/migrations", "-database",  "postgres://user:password@postgres/gophermart?sslmode=disable", "up" ]
    depends_on:
      - postgres
    networks:
      - internal

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    restart: always
    environment:
      - PGADMIN_DEFAULT_EMAIL=gopher@mart.loc
      - PGADMIN_DEFAULT_PASSWORD=password
    ports:
      - '9090:80'
    networks:
      - internal
